name: teenytinytwodee
description: A rapid prototyping framework for 2D games
version: 1.0.0
repository: https://github.com/alexayers/teenytinytwodee-dart
authors:
  - Alex Ayers

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
